on: [push]

jobs:
  az-login:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
      id: login
    - run: echo "Filler output"

  resmanager:
    runs-on: ubuntu-latest
    steps:
    - uses:
      with:
        connection-string: "host=new-server.postgres.database.azure.com port=5432 dbname={your_database} user=anishpoddar2307@new-server password={your_password} sslmode=require"
        sqlfile: 'sql[0-9]\.sql'