on: [push]

jobs:
  az-login:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
      id: login
    - run: echo "Filler output"